#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

ENV_FILE="local.properties"   # 构建从 local.properties 读凭据（app/build.gradle.kts）

banner "OC Beacon 错误上报 · GitHub App 注册"

# ── Stage 1: 注册 GitHub App ─────────────────────────────────────────────
stage "注册 GitHub App"
say "在 GitHub 上创建 App（一次性，~3 分钟）。App 仅用于错误上报：Issues 读写 + device flow 授权。"
open_url "https://github.com/settings/apps/new"
step "GitHub App name 填：OC Beacon Error Report（可自定义，但后续页面按此名找）"
step "Homepage URL 填：https://github.com/LeoNardo-LB/oc-beacon"
step "Webhook - Active 勾选框【取消勾选】（不需要 webhook，留空 URL 即可）"
step "Permissions → Repository permissions → Issues 选【Read & write】"
step "Identifying and authorizing users → 勾选【Enable Device Flow】（关键——8 位码授权依赖它）"
step "同区域若出现 Expire user authorization tokens 选项【不勾选】（一次授权永久有效）"
step "页面底部 Create GitHub App"
pause "创建完成后按回车（浏览器会跳到 App 设置页）"

# ── Stage 2: Client ID ───────────────────────────────────────────────────
stage "捕获 Client ID"
say "App 设置页 General 标签顶部就是 Client ID（约 32 位字符串，Iv1./Iv2. 开头）。"
step "复制 Client ID"
ask GITHUB_APP_CLIENT_ID "粘贴 Client ID："
write_env GITHUB_APP_CLIENT_ID "$GITHUB_APP_CLIENT_ID"
set_secret APP_GITHUB_CLIENT_ID "$GITHUB_APP_CLIENT_ID"

# ── Stage 3: Client Secret ───────────────────────────────────────────────
stage "生成并捕获 Client Secret"
say "同一页面下方 Client secrets 区域。"
step "点 Generate a new client secret"
step "生成后立即点 Copy 复制（离开页面后前缀被掩码）"
ask_secret GITHUB_APP_CLIENT_SECRET "粘贴 Client Secret："
write_env GITHUB_APP_CLIENT_SECRET "$GITHUB_APP_CLIENT_SECRET"
set_secret APP_GITHUB_APP_CLIENT_SECRET "$GITHUB_APP_CLIENT_SECRET"

# ── Stage 4: 安装到仓库 ──────────────────────────────────────────────────
stage "安装 App 到仓库"
say "App 需要安装到目标仓库才能建 issue。"
open_url "https://github.com/settings/apps"
step "找到 OC Beacon Error Report → Edit App → 左侧 Install App"
step "Install → 选 LeoNardo-LB → Only select repositories → 勾选 oc-beacon → Install"
pause "安装完成后按回车"

# ── Stage 5: device flow 端点自动验证 ────────────────────────────────────
stage "验证 device flow（自动）"
say "用刚写入的凭据向 GitHub 设备授权端点发起一次请求——验证凭据与 Device Flow 开关。"
RESP=$(curl -s -m 15 -X POST -d "client_id=$GITHUB_APP_CLIENT_ID" https://github.com/login/device/code || true)
if printf '%s' "$RESP" | grep -q 'device_code'; then
  printf '  %s✓ 端点响应含 device_code — 凭据与 Device Flow 配置正确%s\n' "$GREEN" "$RESET"
  note "（未完成授权轮询，不消耗任何配额）"
else
  warn "端点未返回 device_code，响应片段：$(printf '%s' "$RESP" | head -c 200)"
  say "常见原因：Device Flow 未勾选（回 Stage 1 的 App 设置页补勾）、Client ID 抄错。"
  confirm "已修复后重试？" && RESP=$(curl -s -m 15 -X POST -d "client_id=$GITHUB_APP_CLIENT_ID" https://github.com/login/device/code || true)
  printf '%s' "$RESP" | grep -q 'device_code' || warn "仍未通过——检查后可重跑本向导（已写入的值会保留）"
fi

# ── Stage 6: 重建与真机验证指引 ──────────────────────────────────────────
stage "重建 + 真机验证"
say "凭据已就位。让 App 用上它们："
step "重建开发包：./gradlew :app:assembleDevRelease"
step "安装：adb install -r app/build/outputs/apk/dev/release/app-dev-release.apk"
step "真机：设置 → 诊断 → 菜单「上报到 GitHub」→ 应出现 8 位码授权页（不再是「未配置」占位）"
step "完成授权 → 预览（此时可见带 (#xxxxxxxx) 签名的 issue 标题）→ 提交 → 到仓库确认 issue 创建"
note "CI 侧无需再动：release.yml 已从 secrets APP_GITHUB_CLIENT_ID/SECRET 注入。"
pause "按回车结束"

finish
